-- Replace the "NAME" by your user. NOT DISPLAY USER!

while wait() do
    game.Workspace.NAME.Humanoid.MaxHealth = math.huge
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    forcefield:remove()
    local forcefield =Instance.new("ForceField",game.Players.LocalPlayer.Character)
    wait()
    forcefield:remove()
    end